# These are supported funding model platforms

github: [tejuiceB, psDawake]  # Project maintainers
ko_fi: tejuiceb  # Updated Ko-fi username
custom: [
  'https://t.me/+TwGNOCbIKrM5M2I1',  # Community support channel
  'https://paypal.me/tejubh01?country.x=IN&locale.x=en_GB'  # PayPal link
]
