blank_issues_enabled: false
contact_links:
  - name: PlaylistConverter Community Support
    url: https://t.me/+TwGNOCbIKrM5M2I1
    about: Join our Telegram community for quick help
  - name: Documentation
    url: https://github.com/tejuiceB/PlaylistConverter/wiki
    about: Check our documentation for guides and troubleshooting
