name: PlayList Converter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
      fail-fast: false  # Allow other jobs to continue if one fails

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: 'maven'
        java-package: 'jdk'
        check-latest: true

    - name: Maven Dependency Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/example
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Check application.properties
      run: |
        if [ ! -f "src/main/resources/application.properties" ]; then
          echo "Creating application.properties from template"
          cp src/main/resources/application.properties.template src/main/resources/application.properties || exit 1
        fi
        sed -i "s|REDIRECT_URI=.*|REDIRECT_URI=${{ secrets.REDIRECT_URI }}|g" src/main/resources/application.properties

    - name: Build with Maven
      run: |
        ./mvnw -B clean verify
      env:
        MAVEN_OPTS: "-Xmx4g"

    - name: Run Tests
      run: mvn test

    - name: Generate JaCoCo Coverage Report
      run: mvn jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4  # Updated to v4
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}  # Added token for security

    - name: SonarCloud Analysis
      if: matrix.java == '17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=playlist-converter \
        -Dsonar.organization=your-org \
        -Dsonar.host.url=https://sonarcloud.io

    - name: Check Dependencies
      run: mvn dependency-check:check

    - name: Upload Build Artifact
      if: matrix.java == '17' && success()
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: playlist-converter
        path: target/*.jar
        retention-days: 5  # Added retention period

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4  # Updated to v4
      with:
        name: playlist-converter
        path: target

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/playlist-converter:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/playlist-converter:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/playlist-converter:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/playlist-converter:buildcache,mode=max

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to Production
      run: |
        echo "Add your deployment steps here"
        # Example: Deploy to cloud platform or server
